# Generated by Django 4.2.7 on 2023-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prix', models.FloatField(default=0.0)),
                ('stock', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product')),
            ],
        ),
    ]
